### PR TITLE
Add required asterisks to comment form

### PR DESCRIPTION
**Pull request by AlexGStapleton**
[Related](https://siteorigin.com/thread/no-asterisks-shown-in-comment-fields/)

### CODE REVIEW

**Comment by Misplon** [comment]
Do you perhaps want to modernise the fields a bit? See the $fields section here: https://codex.wordpress.org/Function_Reference/comment_form. I'm just talking about updating the `'fields' => array(`.

**Comment by AlexGStapleton** [comment]
That sounds fine. It may be better just to unset $fields and [use the default](https://codex.wordpress.org/Function_Reference/comment_form#.24fields) - unless there was something specific you want to retain about the current $fields we're using?

**Comment by Misplon** [comment]
Sounds good, thanks mate.

**Comment by AlexGStapleton** [comment]
Oh. I just realized that the Origami comment form uses placeholders for labels. Do you want to proceed with this change (remove the $fields changes) or would you like to copy over most of the structural changes to the comment form manually?

**Comment by Misplon** [comment]
Ahh that's right. All good, we can go with what we have. Thanks.

**Pull request merged**
